name: Back-end Testing, Linting, and Starting

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      working-directory:
        required: true
        type: string
    secrets:
      TEST_JWT_SECRET:
        required: true
      MONGODB_URI:
        required: true

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log inputs
        run: |
          echo "Node version: ${{ inputs.node-version }}"
          echo "Working directory: ${{ inputs.working-directory }}"
  tls:
    needs: log-inputs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    strategy:
      fail-fast: true
      matrix:
        action: ["test-lint", "start"]

    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      PORT: ${{ vars.PORT }}
      TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint and Test
        if: matrix.action == 'test-lint'
        run: |
          npm run lint
          npm run test

      - name: Start
        if: matrix.action == 'start'
        run: |
          npm ci
          npm run start &          
          kill $(jobs -p)
