name: Back-end Testing, Linting, and Starting

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      working-directory:
        required: true
        type: string
    secrets:
      TEST_JWT_SECRET:
        required: true
      JWT_SECRET:
        required: true
      MONGODB_URI:
        required: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - name: Lint and Test
        run: |
          npm ci
          npm run lint
          npm run test

  start:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"

      - name: Start
        run: |
          npm ci
          npm run start &
          sleep 5
          kill $(jobs -p)
