name: Back-end Testing, Linting, and Starting

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      working-directory:
        required: true
        type: string
    secrets:
      TEST_JWT_SECRET:
        required: true
      MONGODB_URI:
        required: true

# defaults:
#   run:
#     working-directory: back
defaults:
  run:
    working-directory: ${{ inputs.working-directory }}

jobs:
  # log-inputs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Log inputs
  #       run: |
  #         echo "Node version: ${{ inputs.node-version }}"
  #         echo "Working directory: ${{ inputs.working-directory }}"
  lint-and-test:
    runs-on: ubuntu-latest

    # needs: log-inputs
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      PORT: ${{ vars.PORT }}
      TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Lint and Test
        run: |
          npm ci
          npm run lint
          npm run test

  start:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directoory: back
    # needs: log-inputs
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      PORT: ${{ vars.PORT }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Start
        run: |
          npm ci
          npm run start &
          sleep 5
          kill $(jobs -p)
