name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # todo delete in real production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  front-end-testing-linting-building:
    uses: bbuukk/live/.github/workflows/back.test_lint_start.yml@main
    with:
      node-version: 20
      working-directory: back
    secrets:
      TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

  back-end-testing-linting-starting:
    uses: bbuukk/live/.github/workflows/front.test_lint_build.yml@main
    with:
      node-version: 20
      working-directory: front
    secrets:
      GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

  back-end-deploy:
    runs-on: ubuntu-latest
    needs:
      [back-end-testing-linting-starting, front-end-testing-linting-building]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: cd back && npm install
      - name: Deploy
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_BACK_PROJECT_ID }}
          vercel-args: "--prod"
          vercel-dir: "back"
  front-end-deploy:
    runs-on: ubuntu-latest
    needs: back-end-deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: cd front && npm install
      - name: Deploy
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_FRONT_PROJECT_ID }}
          vercel-args: "--prod"
          vercel-dir: "front"
