name: Front-end Testing, Linting, and Building

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      working-directory:
        required: true
        type: string
    secrets:
      GOOGLE_ID:
        required: true
      GOOGLE_SECRET:
        required: true
      NEXTAUTH_URL:
        required: true
      NEXTAUTH_SECRET:
        required: true
      DATABASE_URL:
        required: true
      TEST_JWT_SECRET:
        required: true
      JWT_SECRET:
        required: true
      MONGODB_URI:
        required: true

jobs:
  log-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log inputs
        run: |
          echo "Node version: ${{ inputs.node-version }}"
          echo "Working directory: ${{ inputs.working-directory }}"
  tls:
    needs: log-inputs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    strategy:
      fail-fast: true
      matrix:
        action: ["lint-test", "build"]

    env:
      NODE_ENV: ${{ vars.NODE_ENV }}
      PORT: ${{ vars.PORT }}
      NEXT_PUBLIC_BACKEND_URL: ${{ vars.NEXT_PUBLIC_BACKEND_URL }}
      MAINTENANCE_MODE: ${{ vars.MAINTENANCE_MODE }}

      #front-end
      GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      #back-end
      TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint and Test
        if: matrix.action == 'lint-test'
        run: |
          npm run lint
          npm run test

      - name: Start back-end
        if: matrix.action == 'build'
        run: |
          npm ci
          npm run dev &
        working-directory: back

      - name: Build front-end
        if: matrix.action == 'build'
        run: npm run build
