name: Front-end Testing, Linting, and Building

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      working-directory:
        required: true
        type: string
    secrets:
      GOOGLE_ID:
        required: true
      GOOGLE_SECRET:
        required: true
      NEXTAUTH_URL:
        required: true
      NEXTAUTH_SECRET:
        required: true
      DATABASE_URL:
        required: true
      TEST_JWT_SECRET:
        required: true
      JWT_SECRET:
        required: true
      MONGODB_URI:
        required: true

defaults:
  run:
    working-directory: front

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          # cache: "npm"

      - name: Lint and Test
        run: |
          npm ci
          # npm run lint
          # npm run test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          # cache: "npm"

      - name: Start back-end locally
        run: |
          npm ci
          npm run dev &
          sleep 5
        working-directory: back

      - name: Build front-end application
        run: |
          npm ci
          npm run build
