name: JMeter Audit

on:
  push:
    branches: [dev]
  workflow_dispatch: # todo delete in real production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jmeter_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install JMeter
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          rm apache-jmeter-5.6.3.tgz

      - name: Run JMeter Tests
        run: |
          DOMAIN="zhyvyisvit.shop"
          PATHS="/,/products/dlya-kotiv/page=1,/product/-napovniuvahch-khvostyk-3--6l-sylikahelmz-dribnyyu-iz-zelenymy-hranulamy/65b2606f213addb487b8ab13/about,/products/search=dlya-kotiv/page=1"
          IFS=',' read -ra ADDR <<< "$PATHS"
          for PATH in "${ADDR[@]}"; do
              DIRNAME=$(echo $PATH | sed 's/\//_/g')
              mkdir -p "./results/$DIRNAME"
              ./apache-jmeter-5.6.3/bin/jmeter -n -t ./.github/jmeter/test_plan.jmx -Jdomain=$DOMAIN -Jpath=$PATH -l "./results/$DIRNAME/jmeter-results.jtl" -e -o "./results/$DIRNAME/res"
          done

      - name: Archive JMeter results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: ./results/
