name: JMeter Audit

on:
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jmeter_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install JMeter
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          rm apache-jmeter-5.6.3.tgz
          echo "./apache-jmeter-5.6.3/bin" >> $GITHUB_PATHc

      - name: Run JMeter Tests
        run: |
          chmod +x ./.github/jmeter/loading_test.sh
          ./.github/jmeter/loading_test.sh

      - name: Archive JMeter results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: ./results/
