name: Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env: # Define environment variables here
      # JWT_SECRET: ${{ secrets.JWT_SECRET }}
      TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      # NODE_ENV: test
      NODE_ENV: ${{ vars.NODE_ENV }}

    steps:
      - name: Print envs
        run: echo "secret $TEST_JWT_SECRET env $NODE_ENV"
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Change to back-end and run tests
        run: |
          cd back
          npm ci
          npm run test
