name: Test Back-end and Front-end in development environment

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  front-end-testing-linting-building:
    uses: bbuukk/live/.github/workflows/back.test_lint_start.yml@main
    with:
      node-version: 20
      working-directory: back
    secrets:
      TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

  back-end-testing-linting-starting:
    uses: bbuukk/live/.github/workflows/front.test_lint_build.yml@main
    with:
      node-version: 20
      working-directory: front
    secrets:
      GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      TEST_JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
#
#
#? todo deploy to development env
#
#
